apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  replicas: 15
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:3
        ports:
        - containerPort: 8080
        resources:
          requests:
#            memory: "24Mi"
            memory: "5Mi"
          limits:
            memory: "500Mi"

#        livenessProbe:
#          httpGet:
#            path: /index.html
#            port: 80
